name: Deploying documentation

on:
  push:
    branches:
      - master
      - gh-pages

jobs:

  Deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    container: gboldi19/doxygen_env:latest
    steps:
    - uses: actions/checkout@v2
    - run: make doc_generation
    - name: Push git subdirectory as branch
      uses: s0/git-publish-subdir-action@develop

      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: html 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAN: true
