name: Unified testing (DIFFTEST,GTEST,MEMTEST)

on: push

jobs:
  Build_and_compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++-10 -std=c++17 -o a.out *.cpp -lstdc++fs
      - name: Preventing unwanted output append
        run: rm -f output.csv
      - name: Calling program from shell
        run: ./test.sh
      - name: Checking differences
        run: diff output.csv expected_output.csv
      - name: Deleting temporary file
        run: rm -f output.csv

  Memory_test_code_analysis:
    needs: [Build_and_compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cppcheck, Valgrind and Google Test to prevent inclusion error
        run: sudo apt install cppcheck valgrind
      - name: Build phase
        run: g++-10 -std=c++17 -o a.out *.cpp -lstdc++fs
      - name: Gaining rights
        run: chmod a+x ./test.sh ./memtest.sh ./code_analysis.sh
      - name: Calling code analysis
        run: ./code_analysis.sh
      - name: Artifact performance and style messages
        uses: actions/upload-artifact@v2
        with:
          path: ./perf-style_log.txt
      - name: Calling memtest
        run: ./memtest.sh

  Google_test_and_unit_testing:
    needs: [Build_and_compile, Memory_test_code_analysis]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install google test and cmake
        run: sudo apt install libgtest-dev cmake
      - name: Build phase
        run: make google_test
